# Generated by Django 2.2.1 on 2019-07-10 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle', '0024_auto_20190627_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstadoEmprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=0)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('data_emprestimo', models.DateField(auto_now=True)),
                ('data_devolucao', models.DateField(null=True)),
                ('mensagem_rejeitado', models.CharField(max_length=255, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_emprestimo', to='controle.Item')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_emprestimo', to='controle.Usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_emprestimo', to='emprestimo.TipoEstadoEmprestimo')),
            ],
        ),
    ]
