# Generated by Django 2.2.1 on 2019-07-10 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_auto_20190709_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_emprestimo', to='controle.Usuario'),
        ),
    ]
