# Generated by Django 2.2.6 on 2019-11-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0005_auto_20190710_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='mensagem_devolucao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
