# Generated by Django 3.0.4 on 2020-03-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0006_emprestimo_mensagem_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='visualisado',
            field=models.BooleanField(default=0),
        ),
    ]
