# Generated by Django 2.2.1 on 2019-06-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_auto_20190607_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Emprestimo',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='TipoEquipamento',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
