# Generated by Django 2.2.1 on 2019-06-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_emprestimo_item_tipoequipamento_tipousuario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome_user',
            new_name='nome_de_usuario',
        ),
    ]
