# Generated by Django 2.2.1 on 2019-06-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_auto_20190607_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.ImageField(default='static/img/photo.jpg', upload_to='static/img'),
        ),
    ]
