# Generated by Django 2.2.1 on 2019-06-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_auto_20190610_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(default='static/img/photo.jpg', upload_to='imagens/itens/'),
        ),
    ]
