# Generated by Django 2.2.1 on 2019-06-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_auto_20190610_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(default='static/img/sem_imagem.gif', upload_to='imagens/itens/'),
        ),
    ]
