# Generated by Django 2.2.1 on 2019-06-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0009_auto_20190610_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(default='static/img/sem_foto.jpg', upload_to='static/img/'),
        ),
    ]
