# Generated by Django 2.2.1 on 2019-06-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0011_auto_20190610_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(default='static/img/photo.jpg', height_field=200, upload_to='static/img/', width_field=100),
        ),
    ]
