# Generated by Django 2.2.1 on 2019-06-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0012_auto_20190610_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(default='imagens/itens/semimagem.gif', upload_to='imagens/itens/'),
        ),
    ]
