# Generated by Django 2.2.1 on 2019-06-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0013_auto_20190610_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(default='imagens/itens/photo.jpg', upload_to='imagens/itens/'),
        ),
    ]
