# Generated by Django 2.2.1 on 2019-06-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0014_auto_20190610_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(default='imagens/photo.jpg', upload_to='imagens/'),
        ),
    ]
