# Generated by Django 2.2.1 on 2019-06-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0020_auto_20190610_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.FileField(default='documents/sem_foto.jpg', upload_to='documents/%Y/%m/%d'),
        ),
    ]
