# Generated by Django 2.2.1 on 2019-06-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0021_auto_20190611_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.FileField(default='media/sem_foto.jpg', upload_to='documents/%Y/%m/%d'),
        ),
    ]
