# Generated by Django 2.2.1 on 2019-07-11 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0024_auto_20190627_1026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emprestimo',
            new_name='Emprestimo2',
        ),
    ]
