# Generated by Django 2.2.5 on 2019-09-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0026_item_excluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.IntegerField(max_length=15),
        ),
    ]
