# Generated by Django 2.2.5 on 2019-10-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0027_auto_20190930_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
