# Generated by Django 2.2.7 on 2019-12-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0028_auto_20191004_2320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprestimo2',
        ),
    ]
