# Generated by Django 2.2.7 on 2019-12-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0031_auto_20191219_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codigo_tombamento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
