# Generated by Django 2.2.7 on 2020-01-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0032_item_codigo_tombamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo_tombamento',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
