# Generated by Django 2.2.7 on 2020-01-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0033_auto_20200103_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='em_operacao',
            field=models.BooleanField(default=1, null=True),
        ),
    ]
