# Generated by Django 3.0.4 on 2020-04-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0034_item_em_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bloqueado',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
